export const HCP_UTILITY_CHANNELS = [
  { key: 'q6_1_utilita_opuscoli',                    label: 'Opuscoli posta' },
  { key: 'q6_2_utilita_ftof',                        label: 'ISF F2F' },
  { key: 'q6_3_utilita_isf_telefonica',              label: 'ISF Tel.' },
  { key: 'q6_4_utilita_isf_webcall',                 label: 'ISF Webcall' },
  { key: 'q6_5_utilita_email_da_isf',                label: 'Email ISF' },
  { key: 'q6_6_utilita_siti_portali_aziende_con_login', label: 'Portali az.' },
  { key: 'q6_7_utilita_pubblicita_cartacee',         label: 'ADV carta' },
  { key: 'q6_8_utilita_riviste_cartacee',            label: 'Riviste carta' },
  { key: 'q6_9_utilita_sms_mobile',                  label: 'SMS' },
  { key: 'q6_10_utilita_email_aziendali',            label: 'Email az.' },
  { key: 'q6_11_utilita_newsletter_email',           label: 'Newsletter' },
  { key: 'q6_12_utilita_sito_web_di_prodotto',       label: 'Sito prodotto' },
  { key: 'q6_13_utilita_riviste_digitali',           label: 'Riviste dig.' },
  { key: 'q6_14_utilita_social_network',             label: 'Social' },
  { key: 'q6_15_utilita_app_smartphone',             label: 'App' },
  { key: 'q6_16_utilita_app_messaggistica',          label: 'Messagg.' },
  { key: 'q6_17_utilita_webinar',                    label: 'Webinar' },
  { key: 'q6_18_utilita_fad_on_line',                label: 'FAD online' },
  { key: 'q6_19_utilita_congressi_naz_ecm',          label: 'Cong. naz.' },
  { key: 'q6_20_utilita_congressi_inter_ecm',        label: 'Cong. int.' },
]

export const PERF_QUALITY_METRICS = [
  { key: 'q15_1_chiara',               label: 'Chiarezza' },
  { key: 'q15_2_credibile',            label: 'Credibilità' },
  { key: 'q15_3_importante',           label: 'Importanza' },
  { key: 'q15_4_completa',             label: 'Completezza' },
  { key: 'q15_5_nuova',                label: 'Novità' },
  { key: 'q16_probabilita_consiglio',  label: 'P. Consiglio' },
]

export const PERF_CHANNELS = [
  { key: 'q9_1_opuscoli_posta',              label: 'Opuscoli' },
  { key: 'q9_2_isf_ftof',                    label: 'ISF F2F' },
  { key: 'q9_3_isf_telefonica',              label: 'ISF Tel.' },
  { key: 'q9_4_isf_via_webcall',             label: 'ISF Webcall' },
  { key: 'q9_5_email_isf',                   label: 'Email ISF' },
  { key: 'q9_6_portali_aziendali',           label: 'Portali' },
  { key: 'q9_7_adv_riviste_cartacee',        label: 'ADV carta' },
  { key: 'q9_8_articoli_riviste_cartacee',   label: 'Art. carta' },
  { key: 'q9_9_sms_mobile',                  label: 'SMS' },
  { key: 'q9_10_email_aziendali',            label: 'Email az.' },
  { key: 'q9_11_newsletter_email',           label: 'Newsletter' },
  { key: 'q9_12_product_website',            label: 'Sito prod.' },
  { key: 'q9_13_articoli_riviste_digitali',  label: 'Art. dig.' },
  { key: 'q9_14_social_network',             label: 'Social' },
  { key: 'q9_15_app_tematiche',              label: 'App' },
  { key: 'q9_16_app_mess_mobile',            label: 'Messagg.' },
  { key: 'q9_17_webinar',                    label: 'Webinar' },
  { key: 'q9_18_fad_online',                 label: 'FAD' },
  { key: 'q9_19_congressi_naz_ecm',          label: 'Cong. naz.' },
  { key: 'q9_20_congressi_int_ecm',          label: 'Cong. int.' },
]
